name: Build .NET MAUI Android and iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI Workload
        run: dotnet workload install maui

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build MAUI Android
        run: dotnet build VedTetris.csproj -f net8.0-android --configuration Release

      - name: Build MAUI iOS
        run: dotnet build VedTetris.csproj -f net8.0-ios --configuration Release
